[package]
name = "lean-imt"
version = "0.1.0"
edition = "2021"

[features]
append-only = [] # Append-only tree operations. Recommended for zkVM programs.

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }

[dev-dependencies]
rand = "0.8.5"
sha2 = "0.10.8"
